/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicShopifyCallbackRouteImport } from './routes/api/public/shopify/callback'
import { Route as ApiPublicShopifyWebhooksRouteImport } from './routes/api/public/shopify/webhooks'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicShopifyCallbackRoute =
  ApiPublicShopifyCallbackRouteImport.update({
    id: '/api/public/shopify/callback',
    path: '/api/public/shopify/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicShopifyWebhooksRoute =
  ApiPublicShopifyWebhooksRouteImport.update({
    id: '/api/public/shopify/webhooks',
    path: '/api/public/shopify/webhooks',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/shopify/callback': typeof ApiPublicShopifyCallbackRoute
  '/api/public/shopify/webhooks': typeof ApiPublicShopifyWebhooksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/shopify/callback': typeof ApiPublicShopifyCallbackRoute
  '/api/public/shopify/webhooks': typeof ApiPublicShopifyWebhooksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/shopify/callback': typeof ApiPublicShopifyCallbackRoute
  '/api/public/shopify/webhooks': typeof ApiPublicShopifyWebhooksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/api/public/shopify/callback' | '/api/public/shopify/webhooks'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/shopify/callback' | '/api/public/shopify/webhooks'
  id:
    | '__root__'
    | '/'
    | '/api/public/shopify/callback'
    | '/api/public/shopify/webhooks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicShopifyCallbackRoute: typeof ApiPublicShopifyCallbackRoute
  ApiPublicShopifyWebhooksRoute: typeof ApiPublicShopifyWebhooksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/shopify/callback': {
      id: '/api/public/shopify/callback'
      path: '/api/public/shopify/callback'
      fullPath: '/api/public/shopify/callback'
      preLoaderRoute: typeof ApiPublicShopifyCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/shopify/webhooks': {
      id: '/api/public/shopify/webhooks'
      path: '/api/public/shopify/webhooks'
      fullPath: '/api/public/shopify/webhooks'
      preLoaderRoute: typeof ApiPublicShopifyWebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicShopifyCallbackRoute: ApiPublicShopifyCallbackRoute,
  ApiPublicShopifyWebhooksRoute: ApiPublicShopifyWebhooksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
